### ISSUE TITLE
Cannot find module 'monaco-editor\esm\vs\editor\contrib\gotoSymbol\goToCommands'

### ISSUE THREAD

**Issue by Croller** [microsoft/monaco-editor-webpack-plugin#92]
![image](https://user-images.githubusercontent.com/6522167/71412216-c2c92e80-265d-11ea-8f94-2d2503086626.png)

current version 1.7.0, after update to 1.8.1  i get error
using vue js

**Comment by qiufeihong2018** [comment]
me too!I'm have one question

**Comment by BrightLin** [comment]
Me too!

**Comment by mastrayer** [comment]
Me too...

**Comment by Maydisease** [comment]
I also encountered this trouble!
I have try use typescript 3.7.4 -> 3.7.2 
is work!

**Comment by cbbrsc** [comment]
Same problem. I use JS not Typescript.
Any workaround?

**Comment by moander** [comment]
I have the same problem

```
(node:66735) UnhandledPromiseRejectionWarning:   Error: Cannot find module 'monaco-editor/esm/vs/editor/contrib/gotoSymbol/goToCommands'
  
  - loader.js:581 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:581:15
  
  - helpers.js:32 Function.resolve
    internal/modules/cjs/helpers.js:32:19
  
  - index.js:26 resolveMonacoPath
    [backoffice-vue]/[monaco-editor-webpack-plugin]/out/index.js:26:20
  
  - index.js:161 use.options.pre.featurePaths.map
    [backoffice-vue]/[monaco-editor-webpack-plugin]/out/index.js:161:63
  
  - Array.map
  
  - index.js:161 createLoaderRules
    [backoffice-vue]/[monaco-editor-webpack-plugin]/out/index.js:161:43
  
  - index.js:80 MonacoEditorWebpackPlugin.apply
    [backoffice-vue]/[monaco-editor-webpack-plugin]/out/index.js:80:23
  
  - webpack.js:51 webpack
    [backoffice-vue]/[webpack]/lib/webpack.js:51:13
  
  - dev-server.js:30 DevServer.listenCSR
    [backoffice-vue]/[@quasar]/app/lib/dev-server.js:30:22
  
  - dev-server.js:25 resolve
    [backoffice-vue]/[@quasar]/app/lib/dev-server.js:25:16
  
  - new Promise
  
  - dev-server.js:22 DevServer.listen
    [backoffice-vue]/[@quasar]/app/lib/dev-server.js:22:12
  
  - quasar-dev:265 Promise.resolve.then.then.then.then
    [backoffice-vue]/[@quasar]/app/bin/quasar-dev:265:29
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
  
  - loader.js:745 Function.Module.runMain
    internal/modules/cjs/loader.js:745:11
  
  - node.js:283 startup
    internal/bootstrap/node.js:283:19

```

**Comment by SqrtMinusOne** [comment]
Excluding `gotoSymbol` in the config like this: `features: ['!gotoSymbol']` should help

**Comment by ajain27** [comment]
Which config file ? Can you please be more specific ?

**Comment by alexdima** [comment]
`monaco-editor-webpack-plugin` at `1.8.1` can be used to load `monaco-editor` at `^0.19.0`. This is expressed in the peer dependency -- https://github.com/microsoft/monaco-editor-webpack-plugin/blob/7bde413e171fb58f312add5f87bb31e5a4aded0f/package.json#L31

It cannot load older versions of the `monaco-editor`, the reason being that the editor changes its internal shape across versions. 

If you want to load older versions of the `monaco-editor`, you need to use older versions of the `monaco-editor-webpack-plugin`.

**Comment by alexdima** [comment]
@ef4 You are correct, apologies for that.

**Comment by cbbrsc** [comment]
> Excluding `gotoSymbol` in the config like this: `features: ['!gotoSymbol']` should help

It worked for me. Thanks!

**Comment by heygema** [comment]
> Which config file ? Can you please be more specific ?

webpack.config.js
